build-sys: make git-version-gen to work for logrotate project
1) Remove default prefix 'v' because in AC_INIT there is no easy way to
supply empty string as --prefix argument.

2) Do not allow hyphens in version number.  Release version would not have
such, but development time snapshots do and they break Travis rpmbuild step:

  rpmbuild --nodeps -ts logrotate-3.11.0.40-be20.tar.gz
  error: line 3: Illegal char '-' in: Version: 3.11.0.40-be20

This commit makes git-version-gen to drift from gnulib.  If the script is
updated from upstream one should ensure these local modifications do not
disappear in process.

Reported-by: Elan Ruusamäe <glen@delfi.ee>
Signed-off-by: Sami Kerola <kerolasa@iki.fi>